### ISSUE TITLE
Is the out-of-the h1-6 formatting commonly accepted? Looks ugly to me...

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#291] opened 2017-04-07 12:00 UTC
----

**Edit** by @anselmh:  
This is a **duplicate ticket to #279**.

----

This is a revisited topic. And even though my first post regarding this was closed some months ago, I really think that it needs to be brought up again.

I - again - did a little test to check the out-of-the-box h1-h6 formatting, especially when they have a line break. The outcome is really not nice, and the problem seems to be the line-height calculation:

![inuitcss generated h1-h6 css](https://cloud.githubusercontent.com/assets/213803/24798600/116b4a16-1b97-11e7-94b8-95887c7a33a1.png)

As can be seen in the generated css file, the line height of the h2 is the strange 1.71429. The others have 1.3333, 1.2, 1.5. Clearly, the h2 line-height pops out (and I have a strong feeling that it is calculated wrongly!). Also optically:

![inuitcss h1-6 line-heights](https://cloud.githubusercontent.com/assets/213803/24798587/f92750b2-1b96-11e7-94ea-8b73eed24216.png)

The h3 is very narrow, and h6 falls apart again. To me, that dies not look like nice formatting.

I wonder, why it is necessary to calculate new line-heights for each header, anyway, since using one unitless line-height for all headers would yield the perfect, self-adjusting result. Here is a comparison with line-height set to 1.2 for all headers:

![inuitcss-line-height-stable](https://cloud.githubusercontent.com/assets/213803/24798703/924f620c-1b97-11e7-943d-7aae50b8db31.png)

In my opinion, this is a way more natural flow and makes complete sense to my eyes.

May I know, what the idea of the core inuitcss team was/is to calculate separate line-heights for each h*? And are you sure, if the mixin "inuit-font-size" is working properly???

(I know that I can include my own headings calculation; but it's all about consistency out-of-the-box, isn't it?)

**Comment by herzinger** [comment] 2017-04-10 21:33
I'll give a 2 parts response to your issue, and a promise of solution:

1. We calculate the line-height for each font-size to keep with a tidy baseline grid and vertical flow. It's a bit of a extensive topic, so I'll stop here for now;
2. It does fell estrange the way it is now, because the way the current `@inuit-font-size` mixin calculates this is wrong. I talked about it briefly and provided a better demo in [this issue](https://github.com/inuitcss/inuitcss/issues/291);
3. I'm working in the fix/improvement along with a separated, bigger and more complex tool for type management, intended as a separated project, and will submit a pull request as soon as I get some time off. I have always used the optional parameter to set the line-height by hand, based on my own calculations since the first version, but a sizable enough amount of people brought this up recently, here and in the [unofficial slack channel](https://herzinger.typeform.com/to/h6e3Km) I manage, to justify working on a proper, automated solution. I have some pending issues in this project right now, as I do contribute here as a side gig, so sorry for the lateness.

**Comment by rowild** [comment] 2017-04-11 06:38
Thanks for your response! I think you wanted to link to a different issue in "2." (currently it links to this post).
And any chance to find a moment to explain, why a steady vertical flow is only achieved with separate line-heights for each h*? Because I am still convinced that a line-height: 1 is the best solution to my eyes... but then again: I am not a graphic designer...
Thanks for your time!!!

**Comment by florianbouvot** [comment] 2017-05-04 20:44
@rowild the intent of the `inuit-font-size` mixin is to calculate a `line-height` that maintain vertical rhythm.

For more details about vertical rhythm, read [CSS Baseline: The Good, The Bad And The Ugly](https://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly/) by Espen Brunborg (`inuitcss` follow the [The Good: Basic CSS Baseline](https://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly/#the-good-basic-css-baseline) section).

To maintain vertical rhythm the framework use `$inuit-global-line-height` or multiple for `line-height` and spacing. So the mixing return a unites `line-height` equal to `$inuit-global-line-height` or a multiple.

**Comment by rowild** [comment] 2017-06-20 17:28
I just do not understand what should be wrong with "line-height: 1"??? Since it calculates its value according to the font-size, it simply delivers the best result - and does not need any complicated mixin magic, that is not working...

**Comment by anselmh** [comment] 2017-06-27 06:35
> Thanks for your response! I think you wanted to link to a different issue in "2." (currently it links to this post).

Updated the link to the correct ticket number now.

> I just do not understand what should be wrong with "line-height: 1"??? Since it calculates its value according to the font-size, it simply delivers the best result - and does not need any complicated mixin magic, that is not working...

I disagree here. Usually, `line-height: 1` is not very good to read at all. As @herzinger points out the current mixin algorithm is probably going to change for the better and introduce a nicer vertical flow than the current. For me personally, dropping it and replacing it with `line-height: 1` wouldn’t be an option though.

**Comment by csshugs** [comment] 2018-01-04 10:21
`line-height: 1` is indeed not very nice to look at, especially with multiline headings.

Since this issue is a duplicate of #279 and the core question seems to be answered, I close this one and we discuss everything regarding the extensive topic of an improved vertical rhythm in #279 .

**Closed by csshugs** 2018-01-04 10:21 UTC
Labels: duplicate, question

**Comment by herzinger** [comment] 2018-01-28 21:26
As I explained in #279, it's actually not a duplicate. 

This one is an improvement of the vertical rhythm as we have been discussing, and should be reopened, while #279 is actually a feature request. My mistake on understanding the issue was a big part of the confusion, so sorry about that. I'm working on both issues right now.
