### ISSUE TITLE
Proper graphic design baseline.

### ISSUE THREAD

**Issue by kaydwithers** [inuitcss/inuitcss#279] opened 2017-03-06 22:26 UTC
I was wondering if we could do something similar to this https://github.com/michaeltaranto/basekick/blob/master/README.md

I've used it on a project and it works great.

Below is Michaels' presentation on how it can be used.
https://michaeltaranto.github.io/slides-teach-css-to-talk-design/

**Comment by hatzipanis** [comment] 2017-03-08 02:23
Interesting project. We'll give it a run in a future project and see how we go.

**Comment by herzinger** [comment] 2017-03-08 19:32
I'll take a proper look at it later, but on a quick inspection it seems to be pretty unnecessary. If I got it right, it boils down to having a magic number for any font family to translate the text by. You can achieve a proper baseline without it anyway. And this is coming from someone who works as both a delevoper and designer.

**Comment by CelineDesign** [comment] 2017-03-09 07:18
It's about aligning type to baseline like described in [this article](https://medium.com/written-in-code/aligning-type-to-baseline-the-right-way-using-sass-e258fce47a9b#.6zuqfkp88).

> You can achieve a proper baseline without it anyway.

How ?

**Comment by herzinger** [comment] 2017-03-09 14:33
Like this: http://codepen.io/herzinger/pen/KaQoXK

**Comment by CelineDesign** [comment] 2017-03-11 12:58
Thanks for your code, but i can't see the type aligned on the baseline in your example.

**Comment by herzinger** [comment] 2017-03-11 20:54
The left side is the current inuit-font-size, and the right one is part of something I'm working on. Only the later is aligned.

**Comment by anselmh** [comment] 2017-03-22 06:31
@herzinger I think @CelineDesign is probably correct. Given this screenshot, I can confirm that your example does not work in 100% of the cases as it seems, although doing a better job than the current version on the left side: 
![Screenshot from Firefox on macOS showing the right side of herzinger‘s example but not entirely accurately aligning type to the baseline](https://cloud.githubusercontent.com/assets/399345/24185039/569202ba-0ed1-11e7-8b54-7b141f9ab41d.png)

**Comment by herzinger** [comment] 2017-03-22 17:12
@anselmh this 1px variation (for more or for less) happens because of rounding issues, based in the "precision" used in the sass compiler (maximum numbers after decimal points). Either way, even with that the variation is consistent within each element (which is enough to maintain rhythm), each block doesn't break the nexts positioning (which ensures the baseline is followed) and in the ones that have the difference, it's aways negletable.

**Comment by florianbouvot** [comment] 2017-05-04 20:22
If I understand well, the aim is to apply the traditional baseline concept to CSS... For me the framework offers an easy way to maintain rhythm and we need to keep it simple 😉

**Comment by aaronstezycki** [comment] 2017-07-17 13:36
FYI ... Enter the line-height snap property. This is experimental, and doesn't yet have a working spec, but this would solve your problems :)

https://drafts.csswg.org/css-rhythm/examples/snap-height.html

**Comment by nenadjelovac** [comment] 2018-01-28 10:00
@herzinger in your codepen, shouldn't this line:

`$inuit-global-spacing-unit: $inuit-global-baseline-factor + $inuit-global-spacing-multiplier; // 24px`

be

`$inuit-global-spacing-unit: $inuit-global-baseline-factor * $inuit-global-spacing-multiplier; // 24px`?

Former is `10px`, the latter is, indeed, `24px` (as the comment at the end of the line says). After changing that the results for the body text seem similar in both variants (to my eyes anyways, and with the baseline lines turned off), but the headings seem way better in your version.

cc @anselmh

**Comment by herzinger** [comment] 2018-01-28 17:59
@nenadjelovac you are right, this was a typo. However, this line does not affect my version of the mixin per se, it's there just as an example of how to set up the core variables with my approach - and of couse, the base spacing unit between elements was wrong, but not the line-height calculations. Thanks for catching it anyway, I fixed the pen.

**Comment by herzinger** [comment] 2018-01-28 20:26
Thanks for @nenadjelovac's last comment, I went I took another - more careful - look at the presentation and I realized I was actually wrong. It's right that my approach to the font-size mixin is better: it's more correct from a design standpoint and it does result in a better looking typographic flow. That being said, that and the suggestion in this issue are two different things, so I'll open another issue to deal with that (or use the one that was closed), and here is my response to this one:

Basekick, Michael Taranto's project linked above, aims to solve another problem: the way css positions the type in relation to the line-height is different than the way it's positioned in design tools (governed by graphic design principles). CSS aligns the text centered in the line, while graphic design positions the baseline of the characters on the bottom, with descenders (the lower part of letters like `j` or `g` passing into the next line. There are no properties to modify this behavior, so what he does is translate (as to not affect neighboring elements) the text block down a set amount. The thing is: there's also no way to get this "set amount" programmatically, so it requires a magic number, different for each typeface.

Let's leave aside the magic number for now. The first part of his solution is the same as my solution, using the baseline as predefined height lines, with line heights being always multiples of those. This is not surprising, since both solutions are about being closer to design principles. I'll be refining what I already did and submitting a PR for that.

Also, I already was able to reproduce his complete solution using mine as a base, so I'll adapt it to inuitcss and make a proposition about it, but it will include some major changes in the way we deal with type, since I'll have to include not only font-size and line-height, but font-family and the aforementioned translate as well. I ask that this issue remain open for now with that in mind. I'll edit this comment with a pen demonstrating it later today.

**Comment by nenadjelovac** [comment] 2018-01-28 20:56
@herzinger thanks for the effort! Personally, I can't wait to see that PR ;)

>I ask that this issue remain open for now with that in mind. I'll edit this comment with a pen demonstrating it later today.

Could I ask you to please add a new comment with the pen (instead of editing the comment above), so that everyone watching this issue get a notification?

Off/ontopic:

>[…]the **way css positions the type in relation to the line-height is different than the way it's positioned in design tools** (governed by graphic design principles). CSS aligns the text centered in the line, while graphic designers position the baseline of the characters on the bottom, with descenders (the lower part of letters like j or g passing into the next line. There are no properties to modify this behavior, so what he does is translate (as to not affect neighboring elements) the text block down a set amount. The thing is: there's also no way to get this "set amount" programmatically, so it requires a magic number, different for each typeface.

For anyone interested in learning more about the topic, I believe this article goes into depth about challenges @herzinger is talking about 
https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align.

**Comment by herzinger** [comment] 2018-01-29 05:13
@nenadjelovac sure, here it goes:
[Codepen (WIP)](https://codepen.io/herzinger/full/jZNvQm)

The version on the left is the one translated, optimized for the **Roboto** typeface. To the right is the implementation of the font-size mixin for the PR I submited. It's quite math-heavy, and it's a little different from the solution submited by @kaydwithers, since that one works only with absolute pixel value line-heights, and I didn't want to let go of our unitless implementation. It's basically done, in respect to the calculations. What I plan on doing to make it work for us is create a map system to define font-faces and their respective magic numbers.

As you can see in the demo, what I submitted today already comes quite close, and since it envolves lots of decimal points and relatively small nudges, the complete solution is not 100% pixel perfect. Knowing that, my idea is to create a more complete typographic mixin, as to bring more value to the framework than something that will require considerable effort to use correctly (finding the descender ratio for each type in the project), to only be perceptible with an overlay grid over the page and serve only to give designers little satisfaction orgasms. As it stands right now, I don't think it's worth the trouble to include it in inuitcss.

**Comment by KingScooty** [comment] 2018-02-22 15:45
I really like this. Most implementations of vertical rhythm in CSS are done pretty poorly. It would be great to have an implementation done properly bundled with inuit.

**Comment by csshugs** [comment] 2018-02-23 07:24
#349 has landed. The new feature contains a way better handling of the vertical rhythm. However we agreed upon not incorporating the feature of a magic number to align the font pixel-perfect, as this is pretty complex additional code and it's arguable if anyone really measures the pixels or literally lays a vertical grid over the site. Hence, I consider this issue to be solved.

**Closed by csshugs** 2018-02-23 07:24 UTC
Labels: enhancement
