### ISSUE TITLE
Preserve centered items when using stretch layout

### ISSUE THREAD

**Issue by zomars** [inuitcss/inuitcss#293] opened 2017-04-26 19:22 UTC
When using `o-layout--stretch` in conjunction with `o-layout--center` the items are not centered anymore.

**Comment by florianbouvot** [comment] 2017-05-05 18:52
@zomars thank you for identifying this problem.

Using `o-layout--stretch` doesn't preserve this classes : `o-layout--center`, `o-layout--right`, `o-layout--middle`, `o-layout--bottom`, `o-layout--reverse`, (`o-layout--left`).

**Comment by zomars** [comment] 2017-05-05 18:55
I tried to add modifiers for each one but the centered one is the only I could make it behave consistently.

**Comment by florianbouvot** [comment] 2017-05-05 19:01
I will try for fun but I think second solution is better.

**Comment by zomars** [comment] 2017-05-05 19:03
I wanto to agree but I found super convenient to just add the `o-layout--stretch` modifier in most cases, and it justs works fine. But the second approach would make sense.

**Comment by florianbouvot** [comment] 2017-05-05 19:18
There is another issue with `o-layout__item`, child doesn't fill width container : I think we need to add `flex-basis: 100%`.

I will create a CodePen with all case ;)

**Comment by florianbouvot** [comment] 2017-05-05 19:27
After reflexion, I think `o-layout--stretch` can't be combined with `o-layout--middle`, `o-layout--bottom` > that's not a bug.

**Comment by florianbouvot** [comment] 2017-05-05 20:47
I add your work in a new branch and add new fix for `o-layout--right` and `o-layout--left`.

I'm not a Git expert so I hope everything is ok, @anselmh can you take a look when you have time ?

**Comment by herzinger** [comment] 2017-05-12 17:19
>After reflexion, I think o-layout--stretch can't be combined with o-layout--middle, o-layout--bottom > that's not a bug.
- @florianbouvot 

Exactly.

**Comment by anselmh** [comment] 2017-06-27 06:49
@florianbouvot I rebased the branch so now we have the proper git history again. If you want to work on the branch again it’ll say that the "branch diverged", so please do a `git reset --hard origin/tkt-0293` on your local host before doing any changes. This way you get the remote changes with clean, proper history.  
If that branch is now fine, please create a Pull Request and reference and close #294. Authorship, etc. of zomars will all be accounted still in our branch.

**Comment by zomars** [comment] 2017-06-27 17:34
@anselmh do I have to do that or @florianbouvot ?

**Comment by anselmh** [comment] 2017-06-27 18:06
@zomars you don’t need to as you don’t have write permissions to this branch. @florianbouvot needs to take action from here on. Thanks again for your contribution!

**Comment by csshugs** [comment] 2018-01-03 14:43
#308 is merged, so closing this.

**Closed by csshugs** 2018-01-03 14:43 UTC
Labels: enhancement
