### ISSUE TITLE
[utilities.spacing] Use rem based values instead of px

### ISSUE THREAD

**Issue by JonasDoebertin** [inuitcss/inuitcss#273] opened 2017-01-24 20:10 UTC
Just noticed that `utilities.spacing` generates pixel based padding/margin property values only. Wouldn't it be more consistent to use a px/rem combination just like everywhere else?

**Comment by florianbouvot** [comment] 2017-02-27 19:40
@JonasDoebertin we already spoken about this, please see [#167](https://github.com/inuitcss/inuitcss/issues/167#issuecomment-249148255)

**Comment by herzinger** [comment] 2017-03-08 20:07
This does come up and get discussed often, but I do agree it should be changed.

**Comment by anselmh** [comment] 2017-03-22 06:34
I’m going to close this now as it’s a duplicate of #167. Please add your vote or any details on the original issue if you want the idea to be pursued further (_and I personally would encourage you to do so_). Thanks for your input!

**Closed by anselmh** 2017-03-22 06:34 UTC
