### ISSUE TITLE
[objects.ratio] Add contain modifier

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#285] opened 2017-03-22 20:47 UTC
By default content stretches to it container. 
What about adding a modifier that allow content to preserved its aspect ratio and decreases it's size if needed ?

```
.o-ratio__content {
...

  .o-ratio--contain & {
    height: auto;
    width: auto;
    max-height: 100%;
    max-width: 100%;
    margin: auto;
  }

}
```

[CodePen demo](http://codepen.io/florianbouvot/pen/evrBem)

Thoughts ?

**Comment by herzinger** [comment] 2017-03-23 05:35
Yeah, that makes some sense as a modifier.

**Comment by florianbouvot** [comment] 2017-05-05 10:14
Since the opening of this issue, I've work with this modifier: it's work well but **only with images**

So I don't know what to do ?

1. Add this modifier to `o-ratio` object
2. Create a new object *(for image)*
3. Create a plugin *(out of the framework)*
 
Thoughts ?

**Comment by herzinger** [comment] 2017-05-12 17:12
It should work only with images, since video objects don't have "original dimensions" to preserve. Just add to the object and drop a footnote in the comments.

**Comment by aaronstezycki** [comment] 2017-07-12 07:50
Should the container name change from --content to img then ? Rather ambiguous naming if its only meant to be used for images?

**Comment by herzinger** [comment] 2017-07-12 14:12
There's nothing ambiguous. First of all, the inner element is the same whether we use the modifier or not, and only this modifier will work only with images. Second, it's not because it's meant only for images, but because it's function is to preserve the original dimensions, and video objects have no original dimensions to be preserved.

**Comment by florianbouvot** [comment] 2017-07-12 14:16
@herzinger thank you for the clarification.

**Comment by aaronstezycki** [comment] 2017-07-14 12:55
Okay, maybe I've misinterpreted this. When you say video objects have no original dimensions to be preserved what does that mean? 

Also if the object in question that the css changes is specifically an image then surely the naming should reflect that? Otherwise if I put a video in that object because its naming says 'content' (which to me is open to interpretation) and it doesn't work as intended... you'll end up getting github issues from users that don't look at css comments.

**Comment by herzinger** [comment] 2018-01-10 13:06
Sorry, I never saw your follow up question.

Video objects have no specified dimensions when used in html. No width or height inherent to the file itself, you need to specify it. That being the case, it can't be "preserved" in the same way as with images, and that is the reason this modifier fails.

**Comment by csshugs** [comment] 2018-02-26 13:27
#307 is merged.

**Closed by csshugs** 2018-02-26 13:27 UTC
Labels: enhancement
